### ISSUE TITLE
Selecting periodicity of 0 for TDD pattern results in InfinityMbps

### ISSUE THREAD

**Issue by davwheat** [jake-cryptic/5g-speed#4]
This should instead be a validation error.

![image](https://user-images.githubusercontent.com/7406822/130320151-4d0abf7d-e6fb-4876-b0be-d58ea897a201.png)

**Comment by underrobyn** [comment]
Oops, thanks for raising this, I'll write a patch soon.

Thanks!

**Comment by underrobyn** [comment]
Fixed in: https://github.com/jake-cryptic/5g-speed/commit/687d639dc485490f3485c8ec6bda9edb61e760fa
